---
  Receivers:
    -
      Id: LogReceiver-1
      Type: LOG
    -
      Id: LogReceiver-2
      Type: LOG
    -
      Id: LogReceiver-3
      Type: LOG
    -
      Id: SQSReceiver-1
      Type: SQS
      QueueUrl: http://ec-iel-localstack:10001/queue/queue-1
      Config:
        AWS:
          region_name: us-east-1
          endpoint_url: http://ec-iel-localstack:10001
    -
      Id: SQSReceiver-2
      Type: SQS
      QueueUrl: http://ec-iel-localstack:10001/queue/queue-2
      Config:
        AWS:
          region_name: us-east-1
          endpoint_url: http://ec-iel-localstack:10001
  Listeners:
    -
      Id: EventOneListener
      Event:
        Name: EventOne
      Receivers:
        - LogReceiver-1
        - SQSReceiver-1
    -
      Id: EventTwoListener
      Event:
        Name: EventTwo
      Receivers:
        - LogReceiver-2
        - SQSReceiver-2
    -
      Id: EventThreeListener
      Event:
        Name: EventThree
        # Filter:
        #   fromBlock: latest # disable synchronisation using last seen block file
      Receivers:
        - LogReceiver-3
  Worker:
    Blockchain:
      URI: ws://ec-iel-ganache-cli:8585
    General:
      PollingInterval: 5
      ListenerBlocksLogDir: /worker/listener-blocks-log
    Contract:
      ABI:  /contracts/EventEmitter/build/contracts/EventEmitter.json
      Address: /contracts/EventEmitter/address/EventEmitter.address
