version: '3.5'

networks:
  internal:
    name: ec-cd-internal

services:

  localstack:
    image: localstack/localstack
    container_name: ec-cd-localstack
    environment:
      EDGE_PORT: 10001
      HOSTNAME_EXTERNAL: ec-cd-localstack
      SERVICES: 's3'
      DEFAULT_REGION: us-east-1
      LAMBDA_REMOTE_DOCKER: 0
      AWS_ACCESS_KEY_ID: access
      AWS_SECRET_ACCESS_KEY: secretaccess
    restart: on-failure
    networks:
      - internal
    volumes:
      - '${dockerstagedir:-.}/localstack:/docker-entrypoint-initaws.d'

  ganache-cli:
    image: trufflesuite/ganache-cli
    container_name: ec-cd-ganache-cli
    networks:
      - internal
    command: >
        ganache-cli
        --hostname 0.0.0.0
        --port 8585
        --networkId 15
        --blockTime 0
        --secure
        --accounts 5
        --deterministic
        --mnemonic "myth like bonus scare over problem client lizard pioneer submit female collect"

  deployer:
    image: ethereum-channel/contract-deployer/deployer
    container_name: ec-cd-deployer
    build:
      context: ${dockerstagedir:-.}/deployer
      dockerfile: docker/Dockerfile
    volumes:
      - '/deployer/node_modules'
      - '${dockerstagedir:-.}/deployer:/deployer'
      - '${dockerstagedir:-.}/contract:/deployer/contract'
    environment:
      CONTAINER_MODE: container
      SLEEP: 15

      CONTRACT_BUCKET_NAME: contract
      CONTRACT_KEY_PREFIX: contract

      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: access
      AWS_SECRET_ACCESS_KEY: secretaccess
      AWS_ENDPOINT_URL: http://ec-cd-localstack:10001

      TRUFFLE_NETWORK_ID: 15
      TRUFFLE_WALLET_PK: "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d"
      TRUFFLE_BLOCKCHAIN_ENDPOINT: ws://ec-cd-ganache-cli:8585

    networks:
      - internal
